version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: little-bit-docker-frontend
    command: serve -s build -l 3000
    # ports:
    #   - "3000:3000"
    restart: unless-stopped
    networks:
      - little-bit-docker-network

  api:
    build: ./api
    container_name: little-bit-docker-api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    networks:
      - little-bit-docker-network
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: little-bit-docker-auth
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    networks:
      - little-bit-docker-network
    depends_on:
      - auth_db

  api_db:
    image: mongo:latest
    container_name: little-bit-docker-api-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - little-bit-docker-network

  auth_db:
    image: mongo:latest
    container_name: little-bit-docker-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - little-bit-docker-network

  nginx:
    image: nginx:stable-alpine
    container_name: little-bit-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth
    networks:
      - little-bit-docker-network

volumes:
  mongodb_api:
  mongodb_auth:

networks:
  little-bit-docker-network:
    driver: bridge
